# .github/workflows/trigger1.yml
name: Trigger 1

on:
  workflow_dispatch:

jobs:
  trigger-next:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Trigger2
        run: |
          gh workflow run trigger2.yml

