# .github/workflows/trigger2.yml
name: Trigger 2

on:
  workflow_dispatch:

jobs:
  trigger-next:
    runs-on: ubuntu-latest
    steps:
      - name: Call Trigger 3
        run: gh workflow run trigger3.yml
